import type { EditorialArticle } from "./types";

export const cyberSigilism: EditorialArticle = {
  slug: "cyber-sigilism",
  issue: "001",
  title: "Cyber Sigilism",
  seoTitle: "Cyber Sigilism: Cyber Tribal e Neo Tribal | Valentine Tattoo",
  headline: "Cyber Sigilism: guida a Cyber Tribal e Neo Tribal Tattoo",
  topics: ["Cyber Sigilism", "Cybersigilism", "Cyber Tribal Tattoo", "Neo Tribal Tattoo"],
  titleLines: ["Cyber", "Sigilism"],
  subtitle: "Cyber Tribal / Neo Tribal Tattoo",
  dek: "Tra corpo e codice.",
  definition: "Il Cyber Sigilism, scritto anche Cybersigilism, è un’estetica contemporanea del tatuaggio fatta di forme astratte, appuntite e ramificate, spesso tracciate in nero. Intreccia influenze neo tribal, Y2K, cyberpunk e biomeccaniche in composizioni che dialogano con l’anatomia. Una guida al linguaggio, alle sue origini e alle scelte che trasformano un riferimento visivo in un tatuaggio personale.",
  description: "Cyber Sigilism, Cyber Tribal e Neo Tribal: origini, significato, differenze e progetti sul corpo. La guida di Valentine Tattoo, a Triggiano, Bari.",
  datePublished: "2026-10-02",
  dateModified: "2026-10-02",
  readingMinutes: 10,
  cover: {
    src: "/gallery/feed/02",
    alt: "Tatuaggio nero cyber tribal sul braccio, con linee allungate e ramificazioni che seguono la spalla",
    caption: "Linee che seguono il corpo. Lavoro dal portfolio Valentine Tattoo.",
    position: "50% 42%",
  },
  ogImage: "/editorial/cyber-sigilism-og.jpg",
  chapters: [
    {
      type: "definition", id: "linguaggio", label: "Il linguaggio", title: "Una grammatica di spine e vuoti.",
      intro: "Il tatuaggio Cyber Sigilism si riconosce per punte, glifi e linee che si dividono come nervature. Il contrasto tra organico e artificiale conta più di un singolo simbolo: una forma può evocare insieme radici, circuiti e strutture aliene.",
      image: {
        src: "/gallery/feed/08", alt: "Composizione cyber tribal nera sul torace e sulla spalla, con punte curve e ampie porzioni di pelle non tatuata",
        caption: "Organico / artificiale. Una composizione del portfolio Valentine Tattoo.", position: "52% 45%",
      },
      traits: [
        { title: "Linea", text: "Sottile o più marcata, continua o spezzata. Il fine line è frequente, ma non è una regola obbligatoria." },
        { title: "Ramificazione", text: "Le direzioni si moltiplicano. Spine, uncini e curvature costruiscono la tensione della silhouette." },
        { title: "Spazio negativo", text: "La pelle lasciata libera è parte del disegno: separa i tratti e dà respiro alla composizione." },
      ],
    },
    {
      type: "comparison", id: "differenze", label: "Le differenze", title: "Tre nomi. Confini aperti.",
      intro: "Cyber Sigilism e Cyber Tribal si sovrappongono nell’uso contemporaneo. Il Neo Tribal è una famiglia più ampia e precedente. Questi nomi aiutano a orientarsi, ma non sono una tassonomia ufficiale: il portfolio dice più dell’etichetta.",
      styles: [
        { name: "Cyber Sigilism", text: "Forme simili a sigilli, punte e ramificazioni. Un’estetica spesso sottile e grafica, tra immaginario digitale e glifi astratti.", features: "Glifi / linework / ramificazioni" },
        { name: "Cyber Tribal", text: "Silhouette tribal o neo tribal reinterpretate attraverso codici futuristici. Può avere linee più corpose e un carattere cyber-organico.", features: "Flow / futurismo / organico" },
        { name: "Neo Tribal", text: "Forme nere astratte, curve, campiture e vuoti che seguono il corpo. Il movimento occidentale precede il Cybersigilism di decenni.", features: "Blackwork / silhouette / anatomia" },
      ],
      note: "“Tribal Tattoo” e “tatuaggi tribali” sono espressioni ampie. Non rendono intercambiabili il neo tribal occidentale e tradizioni vive come il tā moko Māori o il tatau samoano, che hanno storie e significati propri. Un riferimento culturale va compreso prima di diventare un motivo decorativo.",
      source: "tepapa",
    },
    {
      type: "history", id: "origini", label: "Le origini", title: "Un linguaggio nato da più mondi.",
      intro: "Il Cybersigilism prende forma tra la fine degli anni 2010 e l’inizio dei 2020, ma riunisce riferimenti molto precedenti. Le fonti documentano una scena diffusa, non un unico momento di invenzione.",
      timeline: [
        { era: "1982", title: "Il neo tribal occidentale", text: "Leo Zulueta e Tattoo Time: New Tribalism, pubblicato da Don Ed Hardy, sono riferimenti chiave per il neo tribal contemporaneo: nero, silhouette e rapporto con il corpo.", source: "atlas" },
        { era: "Y2K", title: "Il futuro visto dagli anni 2000", text: "Videogiochi, cyberpunk e revival Y2K alimentano un immaginario di interfacce, creature e tecnologia. Aingelblood cita la cultura videoludica tra i propri riferimenti.", source: "032c" },
        { era: "2010s", title: "Una scena, più geografie", text: "Aingelblood è una delle figure associate alla denominazione Cybersigilism. GQ documenta suoi lavori già nel 2018 a Los Angeles; Berlino è un altro importante contesto di diffusione.", source: "gq" },
        { era: "2022 →", title: "Post-human, nu-tribal, cybersigilism", text: "Dazed descrive nel 2022 un’estetica post-human e nu-tribal. I nomi cambiano e circolano online mentre si incontrano biomeccanico, gothic e club culture.", source: "dazed" },
      ],
      influences: ["H.R. Giger / biomeccanico", "Y2K / videogame culture", "Cyberpunk / futurismo", "Gothic / metal graphics", "Techno / club culture"],
    },
    {
      type: "statement", id: "significato", label: "Il significato", title: "Che cosa significa un sigillo?",
      intro: "I simboli Cyber Sigilism non hanno un significato universale. Un motivo può raccontare un’intenzione personale oppure essere scelto per la sua forma. Non esiste un dizionario condiviso che traduca ogni glifo in protezione, forza o rinascita.",
      statement: "Un segno può essere personale, senza avere una traduzione.",
      paragraphs: [
        "“Sigil” richiama la forma del sigillo e un immaginario simbolico. La storia dei sigilli, anche nelle pratiche associate ad Austin Osman Spare, precede questo linguaggio tattoo; una forma sigil-like non è automaticamente un sigillo occulto.",
        "Nelle interviste raccolte da 032c emergono approcci diversi: per alcuni artisti il simbolo ha un valore rituale, per altri conta soprattutto la ricerca visiva. Il significato, quando c’è, appartiene al progetto e a chi lo porta.",
      ], source: "032c",
    },
    {
      type: "process", id: "progettazione", label: "Il progetto", title: "Il corpo è la prima linea.",
      intro: "Un progetto custom parte dall’anatomia: asse, volume, movimento e spazio disponibile. Simmetria e asimmetria sono scelte compositive. La domanda è come far vivere il disegno sulla pelle, prima ancora di aggiungere dettagli.",
      image: {
        src: "/gallery/feed/07", alt: "Tatuaggio cyber tribal sulla parte alta della schiena, con un nucleo centrale e linee che si aprono verso le spalle",
        caption: "La direzione del disegno dialoga con schiena e spalle. Portfolio Valentine Tattoo.", position: "50% 36%",
      },
      steps: [
        { title: "Ascoltare l’idea", text: "Soggetto, intenzione e riferimenti aiutano a definire la direzione. Una reference serve a spiegare ciò che ti interessa, non a chiedere una copia." },
        { title: "Vedere il disegno sul corpo", text: "Nel processo di Valentine Tattoo, la bozza a pennarello permette di valutare l’insieme sulla zona scelta. Da questa base nasce il disegno definitivo." },
        { title: "Costruire la struttura", text: "Silhouette, direzione delle linee e vuoti devono funzionare insieme. Freehand, disegno digitale e stencil possono essere strumenti complementari." },
        { title: "Dalle ghostlines al tatuaggio", text: "Valentina fissa l’intero stencil con linee molto leggere nella prima seduta di ghostlines. Le sedute successive completano progressivamente il progetto." },
      ],
      note: "Il processo di Valentina è descritto anche nella sezione About del sito. La fotografia mostra un lavoro del portfolio; non è una sequenza documentata delle sedute.",
    },
    {
      type: "placements", id: "placement", label: "Sul corpo", title: "La forma cambia con il placement.",
      intro: "Non esiste una zona migliore per ogni Cyber Sigilism. Il placement cambia scala, direzione e quantità di dettaglio: un disegno sviluppato per la schiena va riprogettato quando passa a un braccio.",
      items: [
        { title: "Schiena / colonna", text: "Un asse verticale da cui far partire ramificazioni verso le scapole. La simmetria può dare struttura; l’asimmetria può creare tensione." },
        { title: "Sterno / torace", text: "La linea mediana e le curve del torace invitano a espansioni laterali. Il disegno va valutato anche con il corpo in movimento." },
        { title: "Braccio / avambraccio", text: "Un volume che ruota: le linee possono allungarsi o avvolgerlo. Conta ciò che si vede da più angolazioni, non solo dalla foto frontale." },
        { title: "Spalla", text: "Una superficie curva che collega torace, schiena e braccio. È utile decidere se il pezzo resterà autonomo o farà parte di un progetto più ampio." },
        { title: "Fianchi / zona lombare", text: "Le curve naturali possono guidare una silhouette orizzontale o obliqua. Il rapporto tra vuoti e linee definisce il ritmo." },
        { title: "Gamba / polpaccio", text: "La direzione longitudinale offre spazio per forme allungate. Curvatura e posizione del corpo cambiano la lettura della composizione." },
      ],
    },
    {
      type: "portfolio", id: "portfolio", label: "Sulla pelle", title: "Dal linguaggio al lavoro reale.",
      intro: "Una selezione di lavori di Valentine Tattoo affini a questo universo visivo. Osserva la direzione delle linee, i vuoti e il rapporto con il corpo: è da qui che può iniziare la conversazione sul tuo progetto.",
      images: [
        { src: "/gallery/feed/02", alt: "Tatuaggio cyber tribal sul braccio con forme nere affilate che seguono spalla e parte superiore dell’arto", caption: "01 / Braccio — linee e volume", position: "50% 40%" },
        { src: "/gallery/feed/06", alt: "Tatuaggio astratto nero sull’avambraccio, con curve intrecciate e spazio negativo tra le linee", caption: "02 / Avambraccio — curve e vuoti", position: "50% 50%" },
        { src: "/gallery/feed/10", alt: "Piccola composizione nera di glifi e punte sulla gamba, dal portfolio di Valentine Tattoo", caption: "03 / Gamba — segno e ramificazione", position: "50% 45%" },
      ],
    },
    {
      type: "longevity", id: "nel-tempo", label: "Nel tempo", title: "Pensare oltre la prima fotografia.",
      intro: "Anche un tatuaggio Cyber Sigilism cambia nel tempo. Scala, distanza tra i tratti, esecuzione, zona e cura della pelle influenzano la leggibilità. Non esiste una durata identica per tutti i lavori, né una promessa di linee immutabili.",
      items: [
        { title: "Progetto leggibile", text: "Un disegno molto piccolo e denso offre meno margine tra i dettagli. Valuta con l’artista dimensioni e vuoti, e chiedi fotografie di lavori guariti quando disponibili." },
        { title: "Fresh e healed", text: "Una foto appena dopo la seduta e una foto a guarigione completata raccontano momenti diversi. Le immagini di questa guida sono un archivio del portfolio, non una prova di resa a distanza di anni." },
        { title: "Cura e protezione", text: "Segui le indicazioni ricevute in studio durante la guarigione. Per la pelle tatuata guarita, l’American Academy of Dermatology raccomanda protezione dai raggi UV con un solare ad ampio spettro SPF 30 o superiore." },
      ], source: "aad",
    },
    {
      type: "artist", id: "valentina", label: "Valentine Tattoo", title: "Il tuo progetto, con Valentina.",
      intro: "Valentine Tattoo è il nome con cui Valentina Stucchi firma il suo lavoro. La tattoo artist riceve a Triggiano presso Crossbone Studio, in provincia di Bari, Puglia. Il suo linguaggio unisce cybertribal, biomeccanico e dark ornamental, con disegni sviluppati su misura.",
      image: { src: "/images/valentina/portrait.webp", width: 959, height: 1199, alt: "Valentina Stucchi, conosciuta come Valentine Tattoo, tattoo artist che riceve a Triggiano presso Crossbone Studio", caption: "Valentina Stucchi / Valentine Tattoo", position: "50% 22%" },
      quote: "Ogni progetto nasce dall’ascolto della tua richiesta e prende forma direttamente sul corpo.",
      paragraphs: [
        "Se cerchi un tatuaggio Cyber Sigilism, Cyber Tribal o Neo Tribal nell’area di Bari, il punto di partenza è una consulenza: racconta l’idea, la zona del corpo e le dimensioni, e aggiungi i riferimenti che ti aiutano a spiegare la direzione visiva.",
        "Il preventivo viene valutato sul singolo progetto. Tiene conto del tempo di progettazione, della prima seduta di ghostlines e delle sedute successive. Puoi esplorare il portfolio e poi usare il modulo di booking per inviare la tua richiesta.",
      ],
    },
  ],
  faqs: [
    { question: "Cybersigilism e Cyber Sigilism sono la stessa cosa?", answer: "Sì. Cybersigilism e Cyber Sigilism sono due grafie della stessa etichetta contemporanea. Non indicano due stili differenti." },
    { question: "Che differenza c’è tra Cyber Sigilism e Cyber Tribal?", answer: "Si sovrappongono spesso. Cyber Sigilism tende a evocare glifi, punte e ramificazioni; Cyber Tribal può descrivere un campo più ampio di composizioni neo tribal futuristiche. I confini non sono ufficiali: guarda i lavori dell’artista per capire il suo linguaggio." },
    { question: "Il Neo Tribal Tattoo è un’antica tradizione?", answer: "No. Il neo tribal occidentale è un movimento contemporaneo, associato a Leo Zulueta e al New Tribalism del 1982. Va distinto dalle tradizioni tatuatorie indigene, che hanno contesti culturali specifici." },
    { question: "Chi ha inventato il Cybersigilism?", answer: "Aingelblood è una delle figure maggiormente associate alla denominazione e ne racconta l’origine nel proprio progetto. Le fonti descrivono però un’estetica sviluppata in più scene: attribuire tutto lo stile a un’unica persona sarebbe una semplificazione." },
    { question: "Un tatuaggio Cyber Sigilism è sempre un sigillo magico?", answer: "No. Una forma può evocare un sigillo senza appartenere a una pratica esoterica. Il significato, quando presente, è personale o definito nel progetto; non esiste una traduzione universale dei simboli Cybersigilism." },
    { question: "Un Cyber Sigilism deve essere simmetrico?", answer: "No. La simmetria è una possibilità, utile per lavorare lungo assi come colonna e sterno. Anche una composizione asimmetrica può appartenere a questo linguaggio." },
    { question: "I tatuaggi Cyber Sigilism invecchiano male?", answer: "Non si può giudicare la resa futura solo dall’etichetta dello stile. Tutti i tatuaggi cambiano: scala, spaziatura, esecuzione e cura incidono sul risultato. Valuta il progetto con l’artista e osserva lavori guariti quando sono disponibili." },
    { question: "Quanto costa un tatuaggio Cyber Sigilism da Valentine Tattoo?", answer: "Il preventivo è individuale. Valentina considera progettazione, prima seduta di ghostlines e sedute successive; dimensione, zona e dettaglio cambiano il tempo necessario. Il modulo di consulenza permette di descrivere l’idea e allegare riferimenti." },
    { question: "Dove riceve Valentina Stucchi?", answer: "Valentina Stucchi, conosciuta come Valentine Tattoo, riceve a Triggiano presso Crossbone Studio, in provincia di Bari, Puglia. Puoi richiedere una consulenza tramite il booking del sito o scriverle su Instagram a @valentine.ttt." },
  ],
  sources: [
    { id: "032c", name: "032c", title: "Cybersigilism: the Forever Trend — interviste ad artisti e contesto visivo", url: "https://magazine.032c.com/magazine/cybersigilism-the-forever-trend" },
    { id: "gq", name: "GQ", title: "What’s a Cybersigilism Tattoo and Why Are You Seeing Them Everywhere?", url: "https://www.gq.com/story/whats-a-cybersigilism-tattoo-and-why-are-you-seeing-them-everywhere" },
    { id: "dazed", name: "Dazed", title: "Grimes’ ‘alien scars’ are fuelling the post-human tattoo trend", url: "https://www.dazeddigital.com/beauty/article/55568/1/grimes-alien-scars-fuel-the-post-human-tattoo-trend" },
    { id: "atlas", name: "Tattoo History Atlas", title: "Tribal and Neo-Tribal Tattoo Style — storia del neo tribal occidentale", url: "https://tattoohistoryatlas.com/styles/tribal/" },
    { id: "tepapa", name: "Te Papa", title: "Tāmoko — storia, pratica e significati nella cultura Māori", url: "https://www.tepapa.govt.nz/digital-museum/explore-digital-museum/maori/tamoko-maori-tattoos-history-practice-and-meanings" },
    { id: "aad", name: "American Academy of Dermatology", title: "Caring for tattooed skin — indicazioni sulla protezione dai raggi UV", url: "https://www.aad.org/public/everyday-care/skin-care-basics/tattoos/caring-for-tattooed-skin" },
  ],
};
